# Project information
site_name: Chateautech Inc.
site_author: Wasim Alayoubi
site_url: https://chateautech.github.io/
docs_dir: ./source
site_dir: ./docs
site_description: >-
  Chateautech Inc. a Canadaian Corporation

# Repository
repo_name: Chateautech Inc.
repo_url: https://github.com/Chateautech 

# Copyright
copyright: Copyright &copy; 2022 - Chateautech Inc.

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github

plugins:
    - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra:
  homepage: https://chateautech.github.io/
  social:
    - icon: fontawesome/brands/slack 
      link: images/dd
    - icon: fontawesome/brands/docker 
      link: images/kk
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better..
  generator: false

nav:
    - Home:
      - Home: index.md
      - Who are we:  who-are-we.md
      - What we do: what-we-do.md
      - Members: the-team.md
    - Products: products.md
    - Services: services.md
    - Customers: customers.md
    - Partners: partners.md
    - Contact us: contact-us.md