# Project information
site_name: Chateautech Inc.
site_author: Chateautech Inc.
site_url: https://www.chateautech.com/
docs_dir: ./source
site_dir: ./docs
site_description: >-
  We are your gateway to innovative solutions.

# Repository
repo_name: Chateautech Inc.
repo_url: https://github.com/Chateautech/
edit_uri: https://github.com/Chateautech/chateautech.github.io/tree/master/source

# Copyright
copyright: Copyright &copy; 2023 - Chateautech Inc.

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.ico
  icon:
    logo: logo
    repo: fontawesome/brands/github

plugins:
    - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra:
  homepage: https://chateautech.github.io/
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/w_alayoubi
    #- icon: fontawesome/brands/docker 
      #link: images/kk
  consent:
    title: Important Notices
    description: >- 
      <p style='text-align: justify;'><b>User agreement:</b></p>
      <p style='text-align: justify;'>Chateautech Inc. website User Agreement shall be applicable to all users of this website. 
      Any use of this website shall be interpreted as your agreement and acknowledgment that you will be bound by such User Agreement.</p>
      <p style='text-align: justify;'>Full User Agreement and Terms of using this website can be read on the Terms/Legal Notice page of our website.</p>

      <p style='text-align: justify;'><b>Cookie consent:</b></p>
      <p style='text-align: justify;'>We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.</p>
      
      
  generator: false

nav:
    - Home: index.md
    - Services: services.md
    - Customers:
      - CleanFuture: cleanfuture.md
      - Diripro: diripro.md
    - Partners: 
      - Tech Minds Consulting: techminds.md
    #- Team: the-team.md
    - Contact us: contact-us.md
    - Terms/Legal Notice: terms.md